version: '3'
volumes:
  data:
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - /e/go-travel-service/nginx/conf.d:/etc/nginx/conf.d
  docker-app-1:
    container_name: service-1
    image: onlyzedsafasdfa/go-travel
    depends_on:
      - mongodb
  docker-app-2:
    container_name: service-2
    image: onlyzedsafasdfa/go-travel
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db